# Site
repository: waisuan/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Evan Sia
title: Senior Software Engineer @ Deliveroo
email: e-sia@outlook.com
phone: "+447578787799"

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  waisuan
linkedin_username: evansia

# Additional icon links
# additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Evan and I'm a software engineer. I am Malaysian and am currently situated in the UK.

  Aside from spending my days writing code and tinkering with interesting pieces of software, I also enjoy searching for good food to eat and lifting semi-heavy weights.

  I have mostly worked on backend systems throughout my career but am capable working in a full stack capacity.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Deliveroo, UK
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: May 2021 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Tech lead of the order-tracker engineering team.
            - Drove the team’s database migration project from ideation to completion; bringing down data storage costs by ~85%.
            - Lead and developed a feature to allow customers to tip their riders through a web interface.
            - Improved the accuracy of the estimated amount of time it would take for an order to arrive at the customer’s address.
            - Enhanced the consumer experience for when an order required more than one rider to deliver to an address.
            - Created software solutions to ensure that the org complied with the regulations defined for delivering orders containing age-restricted products.
            - Developed software to help reduce teams’ operational costs (org-wide).
            - Part of an internal committee that reviews technical design documents produced from within the tech org.
            - <mark>Tech stack</mark>: Ruby, RubyOnRails, Golang, PostgreSQL, DynamoDB, Kafka, Git, Docker, Terraform, AWS
      - layout: left
        title: AlphaSights, UK
        sub_title: Software Engineer
        caption: October 2019 - May 2021
        description: |
            - Part of the Finance & BI engineering team.
            - Introduced QoL features to the internal invoicing and payment system (pagination, PDF rendering, speeding up page load time).
            - Developed an automated system to calculate and generate performance pay for employees.
            - Built DAGs on Apache Airflow to extract data out of OLTP databases and into reports for data analytics.
            - <mark>Tech stack</mark>: Ruby, RoR, Python, Kotlin, PostgreSQL, Airflow, RabbitMQ, Git, Docker, Spinnaker, AWS
      - layout: left
        title: FactSet, UK
        sub_title: Software Engineer
        caption: January 2016 - September 2019
        description: |
            - Designed and executed solutions to process and manage big data sets supplied by financial data vendors.
            - Implemented web services to expose specific financial data sets to client workstations.
            - Maintained and created workflows to automate the retrieval and storage of processed financial data feeds.
            - <mark>Tech stack</mark>: Perl, Bash, C++, Python, Perforce, MySQL

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Clown-CMS
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: Back-end
            icon: fab fa-github
            url: github.com/waisuan/roti
          - title: Front-end
            icon: fab fa-github
            url: github.com/waisuan/clown
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A web app that allows a group of users to to log their sales activity.

          Features include:-
          - Full-text search
          - Server-side pagination
          - File upload/download
          - CRUD capabilities
          - Registration + Login
          - AuthN + AuthZ
          - Admin control panel

          Built with <mark>Angular</mark> as the frontend, <mark>Kotlin</mark> as the backend, and <mark>PostgreSQL</mark> as the data source. The app is hosted on <mark>Heroku</mark> whereas the database resides on <mark>AWS (RDS)</mark>.
      - layout: top-middle
        title: Alfred-bot
        additional_links:
          - title: Source code
            icon: fab fa-github
            url: github.com/waisuan/alfred-bot
        description: | # this will include new lines to allow paragraphs
          A slack bot responsible for helping teams manage their operational rotas; written in <mark>Golang</mark>.

          The bot is currently being actively maintained (by me + in a private repo) and used within my current workplace but an *initial* iteration of its source code/features can be seen under my personal GH repo.

          Features include:-
          - Create a rota.
          - Update a rota's details & settings.
          - View a rota's details & settings.
          - Delete a rota from the channel.
          - Start/Stop a rota shift.
          - Directly override a shift with a different rota member.
          - Schedule a rota shift in advance.
          - Automatically alert the channel when the rota shift changes.
          - Automatically skip over a rota member that's on holiday/OOO.
          - Customize the message shown when the rota shift changes.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Manchester, UK
        caption: 2014 - 2015
        sub_title: MSc Advanced Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: top-middle
        title: RMIT University, Australia
        caption: 2010 - 2013
        sub_title: BSc Computer Science

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: "Lorem Ipsum"

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
